arm_pos_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
  gains:
    j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_finger_joint_l
    - gripper_finger_joint_r
  gains:
    gripper_finger_joint_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_finger_joint_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50

# controller_list:
#   - name: /fr5/arm_controller
#     action_ns: follow_joint_trajectory
#     default: True
#     type: FollowJointTrajectory
#     joints:
#       - j1
#       - j2
#       - j3
#       - j4
#       - j5
#       - j6

#   - name: /fr5/gripper_controller
#     action_ns: follow_joint_trajectory
#     default: True
#     type: FollowJointTrajectory
#     joints:
#       - gripper_finger_joint_l
#       - gripper_finger_joint_r